#!/usr/bin/env bash 
# print domains and subdomains

print_domain_subdomains () {
    dig "$1" +short | while read line; do
        if [[ -n "$line" ]]; then
            echo "The subdomain $2 is an A record and points to $line"
        fi
    done
}

if [ "$#" -eq 2 ]; then 
    print_domain_subdomains "$2.$1" "$2"
else
    print_domain_subdomains "www.$1" "www"
    print_domain_subdomains "lb-01.$1" "lb-01"
    print_domain_subdomains "web-01.$1" "web-01"
    print_domain_subdomains "web-02.$1" "web-02"
fi
