#!/usr/bin/env bash 
# print domains and subdomains

print_domain_subdomains () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { PRINT "The subdomain " $1 " is a " $4 "  record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then 
    print_domain_subdomains "$2.$1" "$2"
else
    print_domain_subdomains "www.$1" "www"
    print_domain_subdomains "lb-01.$1" "lb-01"
    print_domain_subdomains "web-01.$1" "web-01"
    print_domain_subdomains "web-02.$1" "web-02"
fi