#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and then Hi
count=1
while [ $count -le 9 ]; do
    echo "Best School"
	((count ++))
    if [ "$count" -eq 9 ]; then
        echo "Hi"
    fi
done
