#!/usr/bin/env bash
#This script is displays bad luck from China, bad luck from Japan , bad luck from Italy.
count=1
while [ $count -le 20 ]; do
   if [ $count -eq 4 ]; then
     echo "4"
     echo "bad luck from China"
   elif [ $count -eq 9 ]; then
      echo "9"
      echo "bad luck from Japan"
   elif [ $count -eq 17 ]; then
      echo "17"
      echo "bad luck from Italy"
   else
       echo $count
    fi
    ((count++))
done
