#!/usr/bin/env bash
#This script is displays bad luck from China, bad luck from Japan , bad luck from Italy.
count=1
while [ $count -le 20 ]; do
   case $count in
       4)
           echo "4"
           echo "Bad luck from China"
           ;;
       9)
           echo "9"
           echo "Bad luck from Japan"
           ;;
       17)
           echo "17"
           echo "Bad luck from Italy"
           ;;
       *)
           echo $count
           ;;
   esac
   ((count++))
done
