#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes
hour=0
minute=1
while [ $hour -le 12 ]; do
   printf "%02d:%02d\n" $hour $minute
   ((minute++)) 
   if [ $minute -eq 60 ]; then
       minute=0
       ((hour++))
   fi
done | head -n 70
