#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes
hour=0
minute=0
# While loop to display time
while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    
    for (( minute = 0; minute < 60; minute++ )); do
        echo "$minute"
    done

    ((hour++))
done
